version: '3'
services:
  test-city-backend:
    build: ./data_collector
    image: test-city-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data_collector/data:/usr/src/code-is-beautiful/data_collector/data:rw