version: '3'
services:
  minio:
    container_name: Minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_DEFAULT_BUCKETS=review-image
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - /tmp/minio:/data
    restart: unless-stopped

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./data/results/:/init/results
      - ./data/pit-reports/:/init/pit-reports
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set local http://minio:9000 admin supersecret;
        mc mb local/results;
        mc mb local/pit-reports;
        mc anonymous set download local/pit-reports;
        echo 'Uploading data to results...';
        mc cp --recursive /init/results/ local/results/;
        echo 'Uploading data to pit-reports...';
        mc cp --recursive /init/pit-reports/ local/pit-reports/;
        echo 'Upload complete!';
      "

  server:
    build:
      context: ./
      dockerfile: data_collector/Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - minio
    volumes:
      - ./data_collector:/app/data_collector
    env_file:
      - docker-environment.env
    restart: unless-stopped

  java-server:
    build:
      context: block-extractor/
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: unless-stopped

  frontend:
    build:
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - server
    volumes:
      - ./visualizer:/usr/src/app/visualizer
    restart: unless-stopped


