spring.application.name=block
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-request-size=1000GB
spring.servlet.multipart.max-file-size=1000GB
# Jetty limits
server.jetty.max-http-form-post-size=20000000000
server.jetty.connection-idle-timeout=600000